### PR TITLE
Week5作業繳交

### PR DESCRIPTION
**Pull request by JoycexChan**
陳雅君
http://54.234.123.146:8000/
http://54.234.123.146:8000/attraction/10 
http://54.234.123.146:8000/booking

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
- The booking page should force redirecting a not signed-in user to homepage.
- Layout width of the booking page exceeds screen width in small to middle size of devices.
- Your booking page always calls User Auth API 2 times. 1 time User Auth API call can meet all the requirements.

**Comment by JoycexChan** [comment]
> * The booking page should force redirecting a not signed-in user to homepage.
http://54.234.123.146:8000/booking
修改測試會返回首頁

> * Layout width of the booking page exceeds screen width in small to middle size of devices.
修改完畢，符合題目要求10px邊距

> * Your booking page always calls User Auth API 2 times. 1 time User Auth API call can meet all the requirements.
image

老師抱歉錯誤比較多，對JS跟CSS檔案進行了拆分，先繳交作業，還沒拆到的會繼續完成。

陳雅君
http://54.234.123.146:8000/
http://54.234.123.146:8000/attraction/10
http://54.234.123.146:8000/booking

**Review by cwpeng — CHANGES_REQUESTED** [review]
Layout width of the booking page exceeds screen width in small to middle size of devices.
54 234 123 146_8000_booking

**Comment by JoycexChan** [comment]
> Layout width of the booking page exceeds screen width in small to middle size of devices.

好的，已修改內部過大元件，目前大中小螢幕的媒體響應，均不會在底部看到橫向捲軸，
再麻煩老師了，謝謝。

陳雅君
http://54.234.123.146:8000/
http://54.234.123.146:8000/attraction/10
http://54.234.123.146:8000/booking

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
